name: Tests

on:
    pull_request:
        branches: [main]
    push:
        branches: [main]
jobs:
    docker_tests:
        runs-on: ubuntu-22.04
        timeout-minutes: 5

        steps:
            -   uses: actions/checkout@v4
            -   name: Composer cache
                uses: actions/cache@v4
                env:
                    cache-name: cache-composer
                with:
                    path: ~/.cache/composer/
                    key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./composer.json') }}
                    restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

            -   name: Composer init
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.2'
                    coverage: none
                    tools: composer:v2

            -   run: composer install --ansi
            -   run: composer ecs
            -   run: composer phpstan
            -   run: composer tests
            -   run: php examples/wordNet.php word
